DROP DATABASE IF EXISTS 2109013290_MovieCo;
CREATE DATABASE  2109013290_MovieCo;
USE 2109013290_MovieCo;

CREATE TABLE MEMBERSHIP (
	MEM_NUM INT(3) PRIMARY KEY,
    MEM_FNAME VARCHAR(20),
    MEM_LNAME VARCHAR(20),
    MEM_STREET VARCHAR(40),
    MEM_CITY VARCHAR(20),
    MEM_STATE CHAR(2),
    MEM_ZIP INT(5),
    MEM_BALANCE INT
);
CREATE TABLE RENTAL (
	RENT_NUM INT(4) PRIMARY KEY,
    RENT_DATE DATE,
    MEM_NUM INT(3),
    
     #Aðkomulyklar
	CONSTRAINT MEM_NUM_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP(MEM_NUM)
);
CREATE TABLE PRICE (
	PRICE_CODE INT(1) PRIMARY KEY,
    PRICE_DESCRIPTION VARCHAR(50),
    PRICE_RENTFEE DOUBLE(2,1),
    PRICE_DAILYLATEFEE DOUBLE(2,1)
);
CREATE TABLE MOVIE (
	MOVIE_NUM INT(4) PRIMARY KEY,
    MOVIE_NAME VARCHAR(40),
    MOVIE_YEAR YEAR,
    MOVIE_COST DOUBLE(5,2),
    MOVIE_GENRE VARCHAR(15),
    PRICE_CODE INT(1),
    
    #Aðkomulyklar
	CONSTRAINT PRICE_CODE_FK FOREIGN KEY (PRICE_CODE) REFERENCES PRICE(PRICE_CODE)
);
CREATE TABLE VIDEO (
	VID_NUM INT(5) PRIMARY KEY,
    VID_INDATE DATE,
    MOVIE_NUM INT(4),
    
    #Aðkomulyklar
	CONSTRAINT MOVIE_NUM_FK FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM)
);
CREATE TABLE DETAILRENTAL (
	RENT_NUM INT(4),
    VID_NUM INT(5),
    DETAIL_FEE DOUBLE(2,1),
    DETAIL_DUEDATE DATE,
    DETAIL_RETURNDATE DATE,
    DETAIL_DAILYLATEFEE INT(1),
    
    #Aðkomulyklar
	CONSTRAINT RENT_NUM_FK FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM),
    CONSTRAINT VID_NUM_FK FOREIGN KEY (VID_NUM) REFERENCES VIDEO(VID_NUM)
);