# 3
SELECT MOVIE_NAME, MOVIE_YEAR, MOVIE_COST FROM MOVIE WHERE MOVIE_NAME LIKE "%hope%" ORDER BY MOVIE_NAME ASC;

#4
SELECT MOVIE_NAME, MOVIE_YEAR, MOVIE_GENRE FROM MOVIE WHERE MOVIE_GENRE = "ACTION";

#5
SELECT MOVIE_NUM, MOVIE_NAME, MOVIE_COST FROM MOVIE WHERE MOVIE_COST > 40.00;

#6
SELECT MOVIE_NUM, MOVIE_NAME, MOVIE_COST, MOVIE_GENRE FROM MOVIE WHERE MOVIE_COST < 50.00 AND (MOVIE_GENRE = "ACTION" OR MOVIE_GENRE = "COMEDY") ORDER BY MOVIE_GENRE ASC;