USE THEMEPARK;

#1
SELECT DISTINCT(DATE_FORMAT
(SALE_DATE, "%a - %d - %m - %y")) AS "sale_date" 
FROM SALES;

#2
SELECT DISTINCT(DATE_FORMAT
(SALE_DATE, "%d/%m/%Y")) AS "sale_date" 
FROM SALES;

#3
SELECT DISTINCT(DATE_FORMAT
(SALE_DATE, "%W-%D of %M %y")) AS "sale_date" 
FROM SALES;

#4
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE MONTH(EMP_DOB) = 11;

