DROP DATABASE IF EXISTS SaleCo;

CREATE DATABASE SaleCo;
USE SaleCo;

#Customer
CREATE TABLE Customer (
    CUS_CODE INT(5),
    CUS_LNAME VARCHAR(20),
    CUS_FNAME VARCHAR(20),
    CUS_INITIAL CHAR(1),
    CUS_AREACODE CHAR(4),
    CUS_PHONE CHAR(8),
    CUS_BALANCE DOUBLE(3,2)
);

#Invoice
CREATE TABLE Invoice (
	INV_NUMBER INT(4),
    CUS_CODE INT(5),
    INV_DATE DATE
);

#Line
CREATE TABLE Line (
	INV_NUMBER INT(4),
    LINE_NUMBER INT,
    PROD_CODE CHAR(8),
    LINE_UNITS INT,
    LINE_PRICE DOUBLE(3,2)
);

#Product
CREATE TABLE Product (
	PROD_CODE CHAR(8),
    PROD_DESCRIPT LONGTEXT,
    PROD_START_SALE_DATE DATE,
    PROD_ON_HAND INT,
    PROD_PRICE DOUBLE(3,2),
    PROD_SALE DOUBLE(3,2),
    VEND_CODE INT(5)
);

#Vendor
CREATE TABLE Vendor (
	VEND_CODE INT(5),
    VEND_NAME VARCHAR(30),
    VEND_CONTACT VARCHAR(20),
    VEND_AREACODE CHAR(4),
    VEND_PHONE CHAR(8),
    VEND_COUNTRY CHAR(2)
);