USE THEMEPARK;

#1
SELECT EMP_FNAME, EMP_LNAME, DATE_FORMAT(EMP_DOB, "%d/%m/%Y") AS "Date of Birth"  FROM EMPLOYEE WHERE DAY(EMP_DOB) = "14";

#2
SELECT FLOOR(DATEDIFF("2008-11-25",EMP_DOB)/365) AS "Years", DATEDIFF("2008-11-25",EMP_DOB)%365 AS "Days" FROM EMPLOYEE;

#3
SELECT CONCAT(SUBSTR(EMP_PHONE,1,3), SUBSTR(EMP_FNAME,1,2)) AS "USER_PASSWORD" FROM EMPLOYEE;