DROP DATABASE IF EXISTS 2109013290_Review;

CREATE DATABASE 2109013290_Review;
USE 2109013290_Review;

#JOB
CREATE TABLE JOB (
	JOB_CODE INT(5) PRIMARY KEY,
    JOB_DESCRIPTION VARCHAR(40),
    JOB_CHG_HOUR DECIMAL(5,2),
    JOB_LAST_UPDATE DATE
);

#EMPLOYEE
CREATE TABLE EMPLOYEE (
	EMP_NUM INT(3) PRIMARY KEY,
    EMP_LNAME VARCHAR(20),
    EMP_FNAME VARCHAR(20),
    EMP_INITIAL CHAR(1),
    EMP_HIREDAT DATE,
    JOB_CODE INT(5),
    EMP_YEAR INT,
    
    #Aðkomulyklar
	CONSTRAINT JOB_CODE_FK FOREIGN KEY (JOB_CODE) REFERENCES JOB(JOB_CODE)
);

#PROJECT
CREATE TABLE PROJECT (
	PROJ_NUM INT(2) PRIMARY KEY,
    PROJ_NAME VARCHAR(20),
    PROJ_VALUE DECIMAL(9,2),
    PROJ_BALANCE DECIMAL(9,2),
    EMP_NUM INT(3),
    
    #Aðkomulyklar
	CONSTRAINT EMP_NUM_PROJECT_FK FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM)
);

#ASSIGNMENT
CREATE TABLE ASSIGNMENT (
	ASSIGN_NUM INT(4) PRIMARY KEY,
    ASSIGN_DATE DATE,
    PROJ_NUM INT(2),
    EMP_NUM INT(3),
    ASSIGN_JOB INT(3),
    ASSIGN_CHG_HR DOUBLE(3,2),
    ASSIGN_HOURS DECIMAL(3,1),
    ASSIGN_CHARGE DECIMAL(5,2),
    
    #Aðkomulyklar
	CONSTRAINT EMP_NUM_ASSIGNMENT_FK FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM)
);