# 1
SELECT * FROM CUSTOMER WHERE CUS_LNAME = "Smith";

# 2
SELECT * FROM VENDOR WHERE EXISTS
(SELECT * FROM PRODUCT WHERE PRODUCT.P_MIN*2 > PRODUCT.P_QOH);

#3
SELECT * FROM PRODUCT WHERE V_CODE IS NOT NULL;

#4
SELECT V_CODE FROM PRODUCT WHERE V_CODE IS NOT NULL;

#5
SELECT DISTINCT V_CODE FROM PRODUCT WHERE V_CODE IS NOT NULL;

#6
SELECT DISTINCT V_CODE, V_NAME FROM VENDOR WHERE V_CODE IN
(SELECT V_CODE FROM PRODUCT WHERE V_CODE IS NOT NULL);

#7
SELECT DISTINCT V_CODE, V_NAME FROM VENDOR WHERE V_CODE NOT IN
(SELECT V_CODE FROM PRODUCT WHERE V_CODE IS NOT NULL);

#8
ALTER TABLE PRODUCT MODIFY COLUMN P_PRICE DECIMAL(9,2);

#9
ALTER TABLE PRODUCT ADD COLUMN P_SALECODE CHAR(1);

#10
ALTER TABLE PRODUCT DROP COLUMN P_SALECODE;

#11
CREATE VIEW `All Products` AS 
    SELECT
        *
    FROM
        PRODUCT
	WHERE
		P_QOH > P_MIN + 10;

#12




DROP VIEW `All Products`;

SELECT * FROM PRODUCT;
SELECT * FROM VENDOR;

